export { Header } from './header/ui/header'
export { MainBlock } from './mainBlock/ui/mainBlock'
export { WhyNoushi } from './whyNoushi/ui/whyNoushi'
export { OurPride } from './ourPride/ui/ourPride'
export { OurCare } from './ourCare/ui/ourCare'
export { Footer } from './footer/ui/footer'